model:
  binaural: true
  attention: true
  use_clstm: true
  use_cbn: true
  masking_mode: 'E'
  rnn_layers: 2
  rnn_units: 128
  win_len: 400
  win_inc: 100
  fft_len: 512
  win_type: 'hann'
  kernel_size: 5
  kernel_num: [16, 32, 64, 128, 256, 256]
  bidirectional: false
  embed_dim: 1024
  num_heads: 32
