# sr: 16000
# noisy_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_trainset_1f
# noisy_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_valset_1f
# noisy_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_testset_1f
# target_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_trainset_1f
# target_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_valset_1f
# target_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_testset_1f
sr: 16000
noisy_training_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_trainset
noisy_validation_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_valset
noisy_test_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_testset
noisy_test_timit_dataset_dir: /raid/R12K41024/BCCTN/Dataset/noisy_testset_timit
target_training_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_trainset
target_validation_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_valset
target_test_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_testset
target_test_timit_dataset_dir: /raid/R12K41024/BCCTN/Dataset/clean_testset_timit
